version: '3'

services:
  app:
    container_name: opl-front-dev
    image: opl-front-dev 
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    ports: 
      - '0.0.0.0:3000:3000'
    volumes:
      - ./src:/app/src
      - ./OPL.sql:/docker-entrypoint-initdb.d/OPL.sql
    environment:
     - NODE_ENV='development'
     - CHOKIDAR_USEPOLLING=true
    networks:
      - development



